SELECT P.PRODUCT_ID AS PRODUCT_ID, P.PRODUCT_NAME AS PRODUCT_NAME,
    O.AMOUNT * P.PRICE AS TOTAL_PRICE
FROM FOOD_PRODUCT P
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m') = '2022-05'
    GROUP BY PRODUCT_ID
    ) AS O
ON O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY TOTAL_PRICE DESC, PRODUCT_ID