SELECT A.FLAVOR
FROM (
    SELECT H.FLAVOR, H.TOTAL_ORDER + J.TOTAL_ORDER AS COUNT
    FROM FIRST_HALF H 
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) J ON H.FLAVOR = J.FLAVOR
    ORDER BY COUNT DESC
) AS A
LIMIT 3